fix srtp_remove_stream to use SSRC in host byte order
cisco/libsrtp pull request #670
Opened 2023-12-27 19:56 UTC by pabuhler

This fixes the inconsistency in SSRC byte order usage in the public api. Now all usage should be in host byte order.

#220

2023-12-27 20:03 UTC, JonathanLennox commented
See @jesup 's comment on #220 at https://github.com/cisco/libsrtp/issues/220#issuecomment-274152974: I don't think changing this while leaving the function name and signature the same is a good idea.  Even at an API-breaking change like 3.0.0, this won't have any compiler warning to tell someone porting to the new API that they need to change something.

2023-12-27 20:19 UTC, pabuhler commented
@JonathanLennox fair point,  so what about the new name, srtp_delete_stream() ?  
Other options could be to change from add/remove to create/destroy ...
Just changing the name though will not ensure people take notice of the change in parameters.

2023-12-27 20:23 UTC, paulej requested changes
I agree with changes like this for consistency. The app developer should never have to call `htons()` or `htonl()` to use the libsrtp APIs, IMO.  I also agree with Jonathan's comment from Randell that we shouldn't make a change that might blindside developers. Perhaps just rename the API slightly? (We could keep both the old and a new one, but I think that's less desirable.  Upgrading SRTP and having a clean interface should not be hard, especially if these kinds of breaking changes are documented in one obvious place.)

2023-12-27 20:33 UTC, paulej commented
Maybe `srtp_stream_add` and `srtp_stream_remove`?  Just changing the order, but I prefer to have the noun before the action in APIs.  APIs are mixed in this regard, too.

2023-12-27 20:45 UTC, pabuhler commented
> Maybe `srtp_stream_add` and `srtp_stream_remove`? Just changing the order, but I prefer to have the noun before the action in APIs. APIs are mixed in this regard, too.

I think I like that, how about, I rename to srtp_stream_remove / add / update and add a note to the documentation of srtp_stream_remove about the change in byte order. It will also end up in the CHANGES file.

Can make a new task to ensure all API's are reviewed for naming consistency.

2023-12-28 00:47 UTC, paulej commented
> I think I like that, how about, I rename to srtp_stream_remove / add / update and add a note to the documentation of srtp_stream_remove about the change in byte order. It will also end up in the CHANGES file.
> 
> Can make a new task to ensure all API's are reviewed for naming consistency.

Sounds good to me.

2024-01-02 21:36 UTC, paulej approved these changes

2024-01-04 07:04 UTC, merged